---
name: 🚀 Feature Request
description: Suggest an idea for this project
about: Suggest an idea for this solution
title: "(module name): (short issue description)"
labels: [enhancement, needs-triage]
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature you'd like
      description: A clear and concise description of the feature you are proposing.
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: |
        Why do you need this feature? For example: "I'm always frustrated when..."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: |
        Suggest how to implement the addition or change. Please include prototype/workaround/sketch/reference implementation.
    validations:
      required: false
  - type: textarea
    id: other
    attributes:
      label: Additional context
      description: |
        Any alternative solutions or features you considered, a more detailed explanation, stack traces, related issues, links for context, etc.
    validations:
      required: false
  - type: input
    id: solution-version
    attributes:
      label: Solution version used
      description: Find from the bottom right corner of solution web console, or the CloudFormation stacks.
    validations:
      required: true
