---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config-$CRI
  namespace: $LOGHUB_NAMESPACE
  labels:
    k8s-app: fluent-bit
data:
  # Configuration files: server, input, filters and output
  # ======================================================
  fluent-bit.conf: |
    [SERVICE]
        Flush                       5
        Daemon                      off
        Log_level                   Info
        Http_server                 On
        Http_listen                 0.0.0.0
        Http_port                   2022
        Parsers_File                parsers.conf
        storage.path                /var/fluent-bit/state/flb-storage/
        storage.sync                normal
        storage.checksum            off
        storage.backlog.mem_limit   5M
    
$LOGHUB_FLUENT_BIT_INPUT_OUTPUT_FILTER
$LOGHUB_FLUENT_BIT_K8S_FILTER
    [FILTER]
        Name                modify
        Match               loghub.*
        Set                 cluster ${CLUSTER_NAME}
    
  parsers.conf: |
    [PARSER]
        Name   json
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%LZ

    [PARSER]
        Name         docker
        Format       json
        Time_Key     container_log_time
        Time_Format  %Y-%m-%dT%H:%M:%S.%LZ
        Time_Keep    On
        
    [PARSER]
        Name        cri_regex
        Format      regex
        Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) ?(?<log>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z    

$LOGHUB_USER_DEFINE_DOCKER_FIRSTLINE_PARSER
$LOGHUB_USER_DEFINE_PARSER
$LOGHUB_USER_DEFINE_MULTILINE_PARSER
