---
apiVersion: v1
kind: Pod
metadata:
  namespace: $LOGHUB_NAMESPACE
  name: app-sidecar
  labels:
    app: app-sidecar
spec: 
  containers:
  # Fluent-bit's container
  - name: fluent-bit
    image: $LOGHUB_FLUENT_BIT_IMAGE
    imagePullPolicy: Always
    env:
      - name: CLUSTER_NAME
        value: "$LOGHUB_EKS_CLUSTER_NAME"
    ports:
      - containerPort: 2022
    resources:
        limits:
          memory: 200Mi
        requests:
          cpu: 500m
          memory: 100Mi
    volumeMounts:
    - name: var-log
      mountPath: /var/log
    - name: var-lib-docker-containers
      mountPath: /var/lib/docker/containers
      readOnly: true
    - name: app-log
      mountPath: $LOGHUB_LOG_PATH  
    - name: fluentbitstate
      mountPath: /var/fluent-bit/state  
    - name: fluent-bit-config
      mountPath: /fluent-bit/etc/ 
      readOnly: true    
  volumes:
  - name: var-log
    hostPath:
      path: /var/log
  - name: var-lib-docker-containers
    hostPath:
      path: /var/lib/docker/containers      
  - name: app-log
    emptyDir: {}
  - name: fluentbitstate
    hostPath:
      path: /var/fluent-bit/state      
  - name: fluent-bit-config
    configMap:
      name: fluent-bit-config-docker   
  serviceAccountName: fluent-bit   