name: GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python3 -m pip install mkdocs==1.3.1            # install mkdocs
          python3 -m pip install mkdocs-material==8.5.3   # install material theme
          python3 -m pip install mkdocs-macros-plugin==0.7.0  # install macros plugin
          python3 -m pip install mkdocs-include-markdown-plugin==3.8.1 # install include-markdown

      - name: Build mkdocs
        run: |
          mkdocs build -f ./docs/mkdocs.en.yml
          mkdocs build -f ./docs/mkdocs.zh.yml
          cp -av ./docs/index.html ./docs/site

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/site